### ISSUE TITLE
Personalgrupp doesn't seem to be a valid enum in the published standard

### ISSUE THREAD

**Issue by niklasskoldmark** [girgen/ss12000v2#104]
https://github.com/girgen/ss12000v2/blob/3b22ba51e32bc13fbb3bf898571dec73e1779daf/common.yaml#L266

**Comment by xandhen** [comment]
The document will be updated in the next revision with this value added. The published YAML file is correct.

**Comment by girgen** [comment]
tillagt i dokumentet.
