### ISSUE TITLE
"Folkbokföringsadress" and "Särskild postadress" has a CO-attribute and two address-lines in SPAR

### ISSUE THREAD

**Issue by niklasskoldmark** [girgen/ss12000v2#105]
What would be the standard way to populate this property from SPAR?

https://github.com/girgen/ss12000v2/blob/3b22ba51e32bc13fbb3bf898571dec73e1779daf/Person.yaml#L177

**Comment by xandhen** [comment]
It would be to combine the two rows from SPAR and separate them with a line break.

**Comment by girgen** [comment]
> It would be to combine the two rows from SPAR and separate them with a line break.
