### ISSUE TITLE
Code_SecurityMarking and Code_ContactInfoType deviates from document

### ISSUE THREAD

**Issue by xandhen** [girgen/ss12000v2#109]
**Code_SecurityMarking**
In the YAML representation the value range for Code_SecurityMarking is:
- Ingen
- Sekretessmarkering
- Skyddad folkbokföring

While in the document it is:
- Normal
- Sekretessmarkering
- Skyddad folkbokföring

The document should be updated to reflect the value range in the YAML representation.

**Code_ContactInfoType**
In the document, Code_ContactInfoType defines a of values used for email addresses and phone numbers on the person object.
In the YAML representation, this enum is replaced by Code_EmailType and Code_PhoneNumberType. Code_EmailType has the same value range as Code_ContactInfoType, but Code_PhoneNumberType has a different value range.
The document should be updated to be consistent with the YAML representation.

**Comment by girgen** [comment]
YAML är korrekt. Dokumentet justeras.
