### ISSUE TITLE
Discrepancy for civicNoNationality

### ISSUE THREAD

**Issue by xandhen** [girgen/ss12000v2#110]
In the YAML specification the value range for the civicNoNationality attribute on Person is referred to being based on ISO 3166-1 alpha-2.

In the standards document, the value range is referred to being based on 3166-1 alpha-3.

**Comment by girgen** [comment]
Oviktigt på så sätt att det inte är värt att bryta kompatibilitet för dess skull.
Möjligen ändra till nästa stora release, men just nu så ändrar vi i dokumentet istället.
