### ISSUE TITLE
Regarding the use of POST for *Lookup requests

### ISSUE THREAD

**Issue by rockymontana** [girgen/ss12000v2#111]
Hello.
My name is Jonas Erlandsson and I work with @vaxjool at IST.

I was looking through the documentation and found that SS12000 is using POST for different types of lookups. A POST request should be used for creating new resources. 
I'm guessing that it's done this way because of the query param length issue in the HTTP protocol? 

In this case I think it would be better if the look up request would create a reusable filtered resource, save it and return an ID and the filtered items, so that it'd be easy to do a proper GET request to that specific ID. That would be more in line with REST.

The current implementation looks like:
https://github.com/girgen/ss12000v2/blob/5484895c316d20078177af55227c09ac2dee1727/paths/persons.yaml#L198-L247

And a change of this could something in line (with pseudo code):

```
personsLookup:
  post:
    tags:
      - Person
    summary: Skapa en filtrerad lista av personer baserat på en lista av ID:n eller personnummer.
    description: >
      Istället för att hämta personer en i taget med en loop
      av GET-anrop så finns det även möjlighet att hämta många personer
      på en gång genom att skicka ett anrop med en lista med önskade personer.
    parameters:
      - $ref: "#/ExpandParameter"
      - $ref: "searchParameters.yaml#/ExpandReferenceNames"
    responses:
      200:
        description: Anropet lyckades.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  - type: string
                persons:
                  $ref: "../Person.yaml#/PersonsExpandedArray"
personsLookup/{id}:
  get:
    tags:
      - Person
    parameters:
      - name: id
        in: path
        required: true
        type: string
    responses:
      200:
        description: Anropet lyckades.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  - type: string
                persons:
                  $ref: "../Person.yaml#/PersonsExpandedArray"
```

**Comment by girgen** [comment]
TIll nästa större version är detta helt rätt och rimligt, men det är tyvärr inte värt att justera nu och därmed helt bryta bakåtkompatibiliteten. Stänger nu men har kvar i åtanke
