### ISSUE TITLE
Missing studyPlans expand parameter compared to scenario C.14 in document

### ISSUE THREAD

**Issue by xandhen** [girgen/ss12000v2#112]
In the standards document there is a scenario C.14 describing the retrieval of a students study plan. In the sequence diagram depicted in this scenario, there is an expand parameter for Syllabus in the call to the /studyPlans endpoint. In the OpenAPI specifications there is no such parameter and the Syllabus information has to be retrieved via a Syllabus lookup call (also depicted in the scenario).

The document or the API specification should be updated to be fully aligned.

**Comment by girgen** [comment]
I mindre relase, ändra dokumentet. Ta med till nästa större att expand vore rimligt på så sätt som det står i PDF:en. Dock tyvärr ej värt att bryta bakåtkompatibiliteten.

**Comment by girgen** [comment]
Fel av mig... det går att lägga till ny funktionalitet utan att bryta befintliga implementationer. Låt oss lägga till expansion här i YAML.

**Comment by girgen** [comment]
fast det är inte värt ändå, vi hänskjuter det till nästa release, och justerar PDF:en
