### ISSUE TITLE
Organization stavas med z på engelska

### ISSUE THREAD

**Issue by niklasskoldmark** [girgen/ss12000v2#21]
Objekttypen Organisation borde heta Organization om det ska vara konsekvent

**Comment by girgen** [comment]
Nej, det gör det inte på brittisk engelska, och det är brittisk engelska som gäller i standardiseringssammanhang. Det finns flera skillnader i stavning mellan brittisk och amerikansk engelska, som exempelvis att enrolment stavas med ett _'l'_ i Storbritannien.
