### ISSUE TITLE
schoolyear allowed values range

### ISSUE THREAD

**Issue by niklasskoldmark** [girgen/ss12000v2#22]
Finns det någon anledning till att schoolyear bara går till 10? Om man vill täcka in K12(eller K13 som det ju kan vara i Sverige om man läser gymnasieingenjör) borde den väl gå till 12 om man vill kunna mappa fältet mot internationella skolsystem.

**Comment by girgen** [comment]
Hej!

Tanken är att skolform används för att sklija grundskola från gymnasium. I gymnasiet går man i årskurs 1, 2 eller 3 med skolformen 'GY'. Det blir mycket tydligare så, speciellt om man blandar in andra skolformen såsom YH och Folkhögskolor.

Med vänlig hälsning,
Palle
