### ISSUE TITLE
Person.yaml:Biologiskförälder?

### ISSUE THREAD

**Issue by niklasskoldmark** [girgen/ss12000v2#23]
I person-schemat står det Biologiskförälder, menar ni inte Juridiskförälder? Adoptivförälder har väl samma funktion som Biologiskförälder i detta sammanhang?

**Comment by girgen** [comment]
Det här repot är verkligen "work in progress", vad som helst kan hända, och just detta är vi mitt uppe i, så det kommer alldeles säkert att ändras. Jag hoppas det kommer klarna. ;-)
