### ISSUE TITLE
Riktning för sortering

### ISSUE THREAD

**Issue by stefan-jonasson** [girgen/ss12000v2#34]
Det är nu inte specificerat vilket håll sorteringen avser för följande typer och fält:

- Persons 
   - DisplayName
- Placements:
   - SchoolType
- Programmes: 
   - Name
   - SchoolType
   - Code
- Resources
   - DisplayName
- Rooms 
   - DisplayName

**Comment by girgen** [comment]
Är det meningsfullt att sortera på namn i omvänd ordning?

Detsamma för skolformer eller koder?

Det bör väl ändå vara tydligt och konsekvent, så det bör väl kanske heta `DisplayNameAsc` antar jag?

**Comment by girgen** [comment]
Alltid Asc eller Desc på sortkey. Beslut!
