### ISSUE TITLE
Expand på organisation saknar stöd i response objektet

### ISSUE THREAD

**Issue by stefan-jonasson** [girgen/ss12000v2#35]
Skall vi beskriva svaret eller ta bort möjligheten?

**Comment by girgen** [comment]
Generellt så tycker jag expand bara är på vissa slags objekt, och jag tycker inte organisation är ett av dem. Man kan argumentera åt båda hållen, men mitt förslag är:

*ta bort möjligheten*

**Comment by girgen** [comment]
Beslut.
