### ISSUE TITLE
AssignmentRole skiljer sig mot Word dokumentet.

### ISSUE THREAD

**Issue by stefan-jonasson** [girgen/ss12000v2#41]
I wordfilen finns assignmentRoles definierat som ett fält tillhörande Duty. 

I Yaml filerna finns denna endast som expand för både duty och student group. 
Skall vi ha den som ett normalt fält i duty? 

Wordfilen säger:
Duty -> assignmentRoles 

Yaml säger: 
Duty -> _embedded -> assignedToStudentGroupAs
StudentGroup -> _embedded -> assignmentRoles

Det finns i yaml definitionen heller inte längre någon möjlighet att koppla assignmentRole till en skolenhet utan denna måste kopplas till en StudentGroup.

Vad gäller?

**Comment by girgen** [comment]
Ska vara _direkt_ på Duty, dvs det är Duty som *äger* relationerna.
För Studentgroup ska det vara med i embed.
För SchoolUnits ska den inte finnas alls, inte ens embed.

**Comment by Jonke** [comment]
förslag på fix  https://github.com/girgen/ss12000v2/pull/50
