### ISSUE TITLE
oneOf pageToken eller filter?

### ISSUE THREAD

**Issue by girgen** [girgen/ss12000v2#55]
Ofta skriver vi om filter-parametrar: "Kan inte kombineras med `pageToken`"

borde vi inte implementera det med `oneOf`?

**Comment by Jonke** [comment]
Går det?

> OpenAPI 3.0 does not support parameter dependencies and mutually exclusive parameters. There is an open feature request at https://github.com/OAI/OpenAPI-Specification/issues/256. What you can do is document the restrictions in the parameter description and define the logic in the 400 Bad Request response. For example, consider the /report endpoint that accepts either a relative date range (rdate) or an exact range (start_date+end_date):

**Comment by girgen** [comment]
Tydligen inte ännu... ;-)
