### ISSUE TITLE
Code_AddressType

### ISSUE THREAD

**Issue by stefan-jonasson** [girgen/ss12000v2#59]
Vi har en diskrepans mellan yaml filerna och word filen.

I Yaml :

Code_AddressType
  - Folkbokföringsadress
  - Vistelseadress
  - Särskildpostadress

I wordfilen:
- Folkbokföring
- Inackorderingsadress
- Fakturaadress

Vilken stämmer?

**Comment by girgen** [comment]
det överenstämmer idag, justerat.
