### ISSUE TITLE
Using allOf to add a description to a $ref

### ISSUE THREAD

**Issue by joesiltberg** [girgen/ss12000v2#88]
In some places a description is added to a ref by using the allOf construct, e.g. for schoolType in Group:
```
    schoolType:
      allOf:
        - description: >
            Beskriver vilken skolform gruppen är tänkt att användas för.
            Denna information är mest relevant för planering och schemaläggning,
            innan gruppen populeras med elever, eftersom  elevens inskrivning är
            ger mer specifik information.
        - $ref: "common.yaml#/components/schemas/SchoolTypesEnum"
```
When I run this through OpenAPI Tools generator, schoolType will be an object with a string, not just a string (which I'm guessing was the intention?) like for instance groupType.

Placing the description outside of the allOf might help, see the discussion here:

https://github.com/OAI/OpenAPI-Specification/issues/2033

but there still seems to be generators that don't support that pattern either.

Perhaps it would be best to skip such descriptions until OAS 3.1 is released (and tooling supports it) with support for $ref and description together (see https://github.com/OAI/OpenAPI-Specification/issues/2033#issuecomment-543973334 )

When the ref references an object (such as is done in OrganisationReference, ActivityReference etc.) it might be less of an issue, at least my generated code looks ok to my (admittedly OpenAPI-inexperienced) eyes.

**Comment by girgen** [comment]
Ser ut som detta är åtgärdat sen 20 april 2020.
