### ISSUE TITLE
Error response for *Lookup

### ISSUE THREAD

**Issue by joesiltberg** [girgen/ss12000v2#97]
The *Lookup methods (personsLookup, groupsLookup, etc.), do not list 400_invalid_id as a response.

Is that intended? Should IDs that don't exist simply be skipped without error? If so it should perhaps be clarified.

**Comment by xandhen** [comment]
> Should IDs that don't exist simply be skipped without error?

400 invalid id is suggested to be used if the id is malformed. If the id does not exists that would correspond to a 404 not found.

**Comment by girgen** [comment]
Ja, det blir en tom lista till svar om inget av ID:na hittats.
