### ISSUE TITLE
Inconsistencies around activities and expand

### ISSUE THREAD

**Issue by joesiltberg** [girgen/ss12000v2#98]
activityById includes an ExpandParameter, so it should probably return an ActivityExpanded rather than an Activity..?

Also "Activities" and "ActivitiesArray" should probably be renamed to "ActivitiesExpanded" and "ActivitiesExpandedArray" respectively for consistency (see for instance PersonsExpanded and GroupsExpanded).

**Comment by joesiltberg** [comment]
duties seem to have the same issues (duty_by_id returns Duty rather than DutyExpanded)

**Comment by xandhen** [comment]
Activities seems to be resolved by Stefans merged PR. Duties duty_by_id seems to still return a non-expanded type and should be updated from what I can see.

**Comment by girgen** [comment]
Commited fix för Duty-
